### ISSUE TITLE
question regarding the implementation of STLpy

### ISSUE THREAD

**Issue by HuaTongXue** [vincekurtz/stlpy#7]
Dear Professor Vince Kurtz
     Hello Professor, I’m sorry to disturb you in your busy schedule. I’m a student of Beijing Institute of Technology(BIT) from China.
Recently, I’m learning the implementation of Signal Temporal Logic. Your code gives me great inspiration. I admire your experiment and achievement very much, but I have encountered some troubles when trying to install Drake even though I strictly follow the document of the installation. Finally I got the stupid problem that my Mac is arm64 which my not support Drake. So I wonder your installation environment, MacOS or linux. I would appreciate it if you could show some installation details. 
    To tackle this problems, I need to change the solver in your code, but I find that the solver named "GurobiMICPSolver" doesn't support the "AddQuadraticCost" module, and the solver named "ScipyGradientSolver" doesn't conclude "AddControlBounds" and "AddStateBounds", resulting the simulation a  poor performance. So is there any possibility to complete the above solvers in the next days. I would appreciate it if you could help me.
Thanks and regards.

**Comment by vincekurtz** [comment]
Thanks for your interest in this software! I'll see what I can do about supporting quadratic costs with the `GurobiMICPSolver`. There isn't really a good way to include control or state bounds with the `ScipyGradientSolver` given the way it sets up an unconstrained shooting problem, but that's probably the least effective solver anyway. In the meantime, you could try installing Drake [with x86_64 emulation](https://github.com/RobotLocomotion/drake/issues/13514). I haven't tried that myself (I'm running Ubuntu), but you can always use the `[drake]` tag on [stackoverflow]( https://stackoverflow.com/questions/tagged/drake) if you have questions about Drake installation. 

(P.S. I'm not a professor, and you can just call me Vince :) )

**Comment by vincekurtz** [comment]
The `GurobiMICPSolver` should now support `AddQuadraticCost`. Pypi and the online docs have been updated accordingly - let me know if that works for you.

**Comment by HuaTongXue** [comment]
Thanks for your patience and impressing work. The Gurobi solver works so well and thanks again for your code that solves my  confusion in the realization of STL and builds a perfect foundation for the further research. What a bravo work!
