### ISSUE TITLE
Random rectangle (create rectangle with vertexes )

### ISSUE THREAD

**Issue by QiyangZ** [vincekurtz/stlpy#9]
Hi @vincekurtz ，
thank you for sharing your code and your nice docs! It's very clear and useful for me!

However I noticed that in your benchmarks, the obstacles and targets are all rectangles(or circles) whose edges are parallel with axis-x or y (e.g. the function `outside_rectangle_formula`). Is that possible to create these rectangles with their vertexes? So that edges of the rectangles can be not parallel with axis but can be random.

Thank you for your reading and looking forward to your reply!

best regards
Qiyang

**Comment by vincekurtz** [comment]
Yes, it's possible to create rectangles (or any polytopes) based on vertices. I just don't have a convenient function for that right now, so you'd have to write a bit of code. The basic idea is to convert the rectangle from vertex form to halfspace form. There are a variety of algorithms for automating this: "cone double description" is the key phrase to search. Drake has [some tools](https://drake.mit.edu/pydrake/pydrake.geometry.optimization.html#pydrake.geometry.optimization.HPolyhedron) for doing this conversion, which might be a good place to start.

**Comment by QiyangZ** [comment]
Hi @vincekurtz ,
recently I write a function that can generate  quadrilateral (convex) based on vertexes, and it was based on the class LinearPredict. So I'd like to close this issue and if anyone need that function, just leave a comment here or notify me. I'd be glad to share the code.
